services:
  - type: web
    name: weather-app
    env: node
    plan: free
    rootDir: .         # ensure Render builds from root
    buildCommand: npm install && npm run build
    startCommand: npx serve -s build
    envVars:
      - key: REACT_APP_WEATHER_API_KEY
        value: 0c6b0c14b9fb457e377e8010c636c50c
